"""Tests for URL generation and validation.

Ensures all generated links point to valid, working pages.
"""

import sys
sys.path.insert(0, ".")

import pytest
import requests
from scraper.data_gov import build_99co_url, build_propertyguru_url, URA_RENTAL_SEARCH_URL


HEADERS = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36"}

# Sample condo names from URA data
SAMPLE_PROJECTS = [
    "THE REGENCY AT TIONG BAHRU",
    "MERAPRIME",
    "ALEXIS",
    "PRINCIPAL GARDEN",
    "AVENUE SOUTH RESIDENCE",
    "QUEENS PEAK",
    "COMMONWEALTH TOWERS",
    "STIRLING RESIDENCES",
]


class Test99coUrlFormat:
    def test_basic_url(self):
        url = build_99co_url(location="Queenstown")
        assert "99.co" in url
        assert "Queenstown" in url

    def test_with_project_name(self):
        url = build_99co_url(project_name="QUEENS PEAK", bedrooms=1)
        assert "99.co" in url
        assert "Queens%20Peak" in url or "Queens+Peak" in url  # title case
        assert "bedroom_num=1" in url

    def test_project_name_title_cased(self):
        """Project names should be title-cased for better search results."""
        url = build_99co_url(project_name="THE REGENCY AT TIONG BAHRU")
        assert "The%20Regency%20At%20Tiong%20Bahru" in url or "The+Regency" in url

    def test_price_range(self):
        url = build_99co_url(location="Bishan", price_min=3000, price_max=3500)
        assert "rental_range=3000-3500" in url

    def test_price_max_only(self):
        url = build_99co_url(location="Bishan", price_max=3500)
        assert "rental_range=any-3500" in url

    def test_all_sample_projects(self):
        for project in SAMPLE_PROJECTS:
            url = build_99co_url(project_name=project, bedrooms=1, price_min=2500, price_max=4000)
            assert "99.co" in url
            assert "bedroom_num=1" in url
            assert "rental_range=2500-4000" in url


class TestPropertyGuruUrlFormat:
    def test_basic_url(self):
        url = build_propertyguru_url(location="Queenstown")
        assert "propertyguru.com.sg" in url
        assert "Queenstown" in url

    def test_with_project_name(self):
        url = build_propertyguru_url(project_name="QUEENS PEAK", bedrooms=1)
        assert "propertyguru.com.sg" in url
        assert "Queens%20Peak" in url or "Queens+Peak" in url
        assert "bedroom_num=1" in url

    def test_project_name_title_cased(self):
        url = build_propertyguru_url(project_name="AVENUE SOUTH RESIDENCE")
        assert "Avenue%20South%20Residence" in url or "Avenue+South" in url

    def test_price_params(self):
        url = build_propertyguru_url(location="Bishan", price_min=3000, price_max=4000)
        assert "minprice=3000" in url
        assert "maxprice=4000" in url

    def test_all_sample_projects(self):
        for project in SAMPLE_PROJECTS:
            url = build_propertyguru_url(project_name=project, bedrooms=1, price_min=2500, price_max=4000)
            assert "propertyguru.com.sg" in url
            assert "bedroom_num=1" in url


class TestUraUrl:
    def test_ura_url_constant_valid(self):
        assert "ura.gov.sg" in URA_RENTAL_SEARCH_URL
        assert "realEstateIIWeb" in URA_RENTAL_SEARCH_URL

    def test_ura_url_reachable(self):
        """URA rental search page should be reachable (not a dead domain or 5xx)."""
        resp = requests.get(URA_RENTAL_SEARCH_URL, headers=HEADERS, timeout=10, allow_redirects=True)
        # URA's Java webapp may return 404 to raw requests but works in browser.
        # Key check: it should NOT redirect to a "Page Not Found" error page.
        assert "Page-Not-Found" not in resp.url
        assert resp.status_code < 500  # server is up


class TestSmartSearchUrls:
    """Test URLs generated by the smart search module."""

    def test_smart_search_results_have_urls(self):
        from smart_search import expand_query
        result = expand_query("SMU附近 1b1b 3300")
        assert result is not None
        for r in result.results[:5]:
            assert "99.co" in r.url_99co
            assert "propertyguru.com.sg" in r.url_propertyguru
            # Project name should be in the URL (title-cased)
            assert r.project_name.split()[0].title() in r.url_99co.replace("%20", " ")

    def test_url_project_names_not_allcaps(self):
        """URLs should use title case, not ALL CAPS (better search results)."""
        from smart_search import expand_query
        result = expand_query("SMU附近 1b1b 3300")
        if result and result.results:
            r = result.results[0]
            # Should NOT have all-caps project name in URL
            assert r.project_name.upper() not in r.url_99co.replace("%20", " ")


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
